Updates

diff --git a/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010 b/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010
--- a/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010
+++ b/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010
@@ -36,9 +36,9 @@ if [[ $# -eq 0 ]]; then
     echo "        and error in flux density also in mJy unit"
     echo "    "
     echo "    The default input flux data file name is \"extracted_flux.txt\"."
-    echo "    We will try to filter out S/N<2 and radio data points and produce a filtered flux data file \"fit_5.in\"."
-    echo "    However, if a \"fit_5.in\" file already exists, we will directly use that and ignore any input of flux file!"
-    echo "    So make sure you delete \"fit_5.in\" file if you want a fresh new fitting with new input flux data file!"
+    echo "    We will try to filter out S/N<2 and radio data points and produce a filtered flux data file \"$FitName.in\"."
+    echo "    However, if a \"$FitName.in\" file already exists, we will directly use that and ignore any input of flux file!"
+    echo "    So make sure you delete \"$FitName.in\" file if you want a fresh new fitting with new input flux data file!"
     echo "    "
     echo "    A new feature: if we prepared a folder named \"best-fit_stellar_SED\", and if there is a file named "
     echo "    \"INDEX_LIB1\" in that folder, then we will fix the stellar SED library index to the value therein, "
@@ -62,8 +62,13 @@ fi
 # 
 Redshift=""
 Parallel=2
+Sampling=10000
 Flux=""
 Umin="" # Added on 2018-03-23 to put an additional constraint on Umin
+NoRadio=0
+Overwrite=0
+FitName="fit_5"
+ObjName="obj"
 if [[ $(hostname) == aida* ]] || [[ $(hostname) == isaac* ]]; then
     Flux="extracted_flux.txt" #<TODO># 
 fi
@@ -99,6 +104,35 @@ if [[ $# -ge 2 ]]; then
                 echo 
                 echo Umin="${!i}"
             fi
+        elif [[ "$Strcmd" == "-sampling" ]]; then
+            if [[ $i -lt $# ]]; then
+                i=$((i+1))
+                Sampling="${!i}"
+                echo 
+                echo Sampling="${!i}"
+            fi
+        elif [[ "$Strcmd" == "-fit-name" ]]; then
+            if [[ $i -lt $# ]]; then
+                i=$((i+1))
+                FitName="${!i}"
+                echo 
+                echo FitName="${!i}"
+            fi
+        elif [[ "$Strcmd" == "-obj-name" ]]; then
+            if [[ $i -lt $# ]]; then
+                i=$((i+1))
+                ObjName="${!i}"
+                echo 
+                echo ObjName="${!i}"
+            fi
+        elif [[ "$Strcmd" == "-no-radio" ]]; then
+            NoRadio=1
+            echo 
+            echo NoRadio=$NoRadio
+        elif [[ "$Strcmd" == "-overwrite" ]]; then
+            Overwrite=$((Overwrite+1))
+            echo 
+            echo Overwrite=$Overwrite
         fi
         i=$((i+1))
     done
@@ -141,22 +175,29 @@ fi
 # 
 # Check photometry file
 # 
-if [[ ! -f "fit_5.in" ]]; then
+if [[ ! -f "$FitName.in" ]] || [[ $Overwrite -ge 2 ]]; then
     if [[ -f "$Flux" ]]; then
         echo ""
         echo ""
-        echo "Warning! \"fit_5.in\" was not found! But found \"$Flux\"! Will run: "
-        echo "michi2_filter_flux_2sigma_no_radio.py \"$Flux\" \"fit_5.in\""
-        echo "to filter flux data points for SED fitting."
-        echo ""
-        michi2_filter_flux_2sigma_no_radio.py "$Flux" "fit_5.in"
+        echo "Warning! \"$FitName.in\" was not found! But found \"$Flux\"! Will run: "
+        if [[ $NoRadio -eq 1 ]]; then
+            echo "michi2_filter_flux_2sigma_no_radio_fit_infrared_upper_limits.py \"$Flux\" \"$FitName.in\""
+            echo "to filter flux data points for SED fitting."
+            echo ""
+            michi2_filter_flux_2sigma_no_radio_fit_infrared_upper_limits.py "$Flux" "$FitName.in"
+        else
+            echo "michi2_filter_flux_2sigma_fit_infrared_upper_limits.py \"$Flux\" \"$FitName.in\""
+            echo "to filter flux data points for SED fitting."
+            echo ""
+            michi2_filter_flux_2sigma_fit_infrared_upper_limits.py "$Flux" "$FitName.in"
+        fi
         echo ""
         echo ""
     fi
 fi
-if [[ ! -f "fit_5.in" ]]; then
+if [[ ! -f "$FitName.in" ]]; then
     echo 
-    echo "Error! \"fit_5.in\" was not found! Please prepare that photometry file which contains 3 columns: wavelengths in um, flux densities in mJy and the errors in flux density in mJy."
+    echo "Error! \"$FitName.in\" was not found! Please prepare that photometry file which contains 3 columns: wavelengths in um, flux densities in mJy and the errors in flux density in mJy."
     exit
 fi
 
@@ -188,33 +229,81 @@ fi
 # 
 # Copy SED LIB
 # 
-echo 
-michi2-deploy-files SED BC03 MullaneyAGN DL07UPD2010
+if [[ ! -f "lib.BC03.Padova1994.BaSeL.Z0.0190.ConstSFH.Age200Myr.EBV.SED" ]] || \
+   [[ ! -f "lib.MullaneyAGN.SED" ]] || \
+   [[ ! -f "lib.DL07.2010.03.18.spec.2.0.HiExCom.SED" ]] || \
+   [[ ! -f "lib.DL07.2010.03.18.spec.2.0.LoExCom.SED" ]] || \
+   [[ ! -f "lib.RadioPowerlaw.Single.SED" ]] || \
+   [[ $Overwrite -ge 2 ]]; then
+    echo 
+    if [[ $NoRadio -eq 1 ]]; then
+        michi2-deploy-files SED BC03.Age200Myr MullaneyAGN DL07UPD2010
+    else
+        michi2-deploy-files SED BC03.Age200Myr MullaneyAGN DL07UPD2010 Radio
+    fi
+fi
 
 
 # 
 # Run michi2
 # 
-echo 
-michi2_v04 -obs "fit_5.in" \
-           -redshift $Redshift \
-           -lib "lib.BC03.Padova1994.BaSeL.Z0.0190.EBV.SED" \
-                "lib.MullaneyAGN.SED" \
-                "lib.DL07.2010.03.18.spec.2.0.HiExCom.SED" \
-                "lib.DL07.2010.03.18.spec.2.0.LoExCom.SED" \
-                "RadioPowerlaw.Single.lib.SED" \
-           -out "fit_5.out" \
-           -parallel $Parallel \
-           ${constrain_stellar_index[@]} \
-           ${constrain_dust_Umin[@]} \
-           -constraint LIB3 INDEX EQ LIB4 INDEX \
-           -constraint LIB5 NORM EQ SED "((LIB3*(10^LIB3_PAR3))+(LIB4*(10^LIB4_PAR3)))*40.31970/3750/10^2.4" \
-           -filter filter.list
-           
-           # -constraint LIB5 NORM EQ SED "LIR(8,1000)*1.061619121e-06" \
-           # calc 1/3750/10**2.4 = 1.061619121e-06, qIR = 2.4. 
+if [[ ! -f "$FitName.out" ]] || [[ $Overwrite -ge 1 ]]; then
+    echo 
+    michi2_v05 -obs "$FitName.in" \
+               -redshift $Redshift \
+               -lib "lib.BC03.Padova1994.BaSeL.Z0.0190.ConstSFH.Age200Myr.EBV.SED" \
+                    "lib.MullaneyAGN.SED" \
+                    "lib.DL07.2010.03.18.spec.2.0.HiExCom.SED" \
+                    "lib.DL07.2010.03.18.spec.2.0.LoExCom.SED" \
+                    "lib.RadioPowerlaw.Single.SED" \
+               -out "$FitName.out" \
+               -parallel $Parallel \
+               -sampling $Sampling \
+               ${constrain_stellar_index[@]} \
+               ${constrain_dust_Umin[@]} \
+               -constraint "LIB3_INDEX = LIB4_INDEX" \
+               -constraint "LIB5_NORM = ((LIB3_NORM*(10^LIB3_PAR3))+(LIB4_NORM*(10^LIB4_PAR3)))*40.31970/3750/10^2.4" \
+               -filter filter.list
+               
+               # 
+               # -constraint LIB5 NORM EQ SED "LIR(8,1000)*1.061619121e-06" \
+               # calc 1/3750/10**2.4 = 1.061619121e-06, qIR = 2.4. 
+               # 
+               # -constraint LIB5 NORM EQ SED "((LIB3*(10^LIB3_PAR3))+(LIB4*(10^LIB4_PAR3)))*40.31970/3750/10^2.4" \
+               # 
+               # -constraint "LIB5_NORM = ((LIB3_NORM*(10^LIB3_PAR3))+(LIB4_NORM*(10^LIB4_PAR3)))*40.31970/3750/10^2.4"
+               # 
+    # 
+    # if we re-ran the fitting, then also clean previous results
+    if [[ -d "results_${FitName}/" ]]; then
+        BackupDate=$(date +"%Y%m%d_%Hh%Mm%Ss_%Z")
+        echo "Backing up \"results_${FitName}/\" as \"results_${FitName}_${BackupDate}/\""
+        mv "results_${FitName}/" "results_${FitName}_${BackupDate}/"
+    fi
+fi
+if [[ ! -f "$FitName.out" ]]; then
+    echo "Error! Failed to run michi2 and produce \"$FitName.out\"!"
+    exit 1
+fi
 
 
+# 
+# Plotting results
+# 
+if [[ ! -f "results_${FitName}/${FitName}.pdf" ]] || [[ $Overwrite -ge 1 ]]; then
+    michi2_plot_SED_fitting_results_for_michi2_v05.py "${FitName}.out" \
+        -out "results_${FitName}/${FitName}.pdf" \
+        -flux "$Flux" \
+        -source "$ObjName"
+fi
+# 
+if [[ ! -f "results_${FitName}/${FitName}.best.pdf" ]] || [[ $Overwrite -ge 1 ]]; then
+    michi2_plot_SED_fitting_results_for_michi2_v05.py "${FitName}.out" \
+        -out "results_${FitName}/${FitName}.best.pdf" \
+        -flux "$Flux" \
+        -source "$ObjName" \
+        -only-best
+fi
 
 
 
