Updates

diff --git a/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010 b/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010
--- a/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010
+++ b/bin/michi2-run-fitting-5-components-with-BC03-SingleAge200Myr-and-MullaneyAGN-and-DL07UPD2010
@@ -291,6 +291,11 @@ if [[ ! -f "$FitName.out" ]]; then
     echo "Error! Failed to run michi2 and produce \"$FitName.out\"!"
     exit 1
 fi
+if [[ $(cat "$FitName.out" | wc -l) -lt 3 ]]; then
+    rm "$FitName.out"
+    echo "Error! Failed to run michi2 and produce \"$FitName.out\"!"
+    exit 1
+fi
 
 
 # 
